### 获取当前用户余额信息
GET http://127.0.0.1:9001/gw/ecommerce-account-service/balance/current-balance
Accept: application/json
ecommerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiSW1vb2NRaW55aUBpbW9vYy5jb21cIn0iLCJqdGkiOiJiNmQ0ZTM0Mi0yNWU1LTQwOGItYTJlMi0xNTI1ZDIyNmE3NjUiLCJleHAiOjE2NTY0MzIwMDB9.A8Xauk27EBNFesTR5qysbEMCbEKEnhEyAO4Q_yNQAlES_WcsTapSRw8WBxUnjuveqJzLSOqn8tS6lu7QhG_BzsDTppnM-AqcE__9YNGA0TjiOHyE9eqWalm74kcY52bMFQgF_yRsZyzGCZq5fmhRlt_XvT_rfawrEai5eHMUYT9DYCny5yWeRlM2pliDSexahqYtjvSLBP8pyTVgEWk8p_ml4iF4fPWYJeryl1K46uV4wKOVJTbH45nczXECI51q5ZO8E5EQMrpwEXqT17BBSLxihdBIomS_zHeXS3QsSCXoSnhxhRJP0QjDPnJLCn6zoa4bZJkCtvlpAT4qpFuxBw

### 扣减用户余额
PUT http://127.0.0.1:9001/gw/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
ecommerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiSW1vb2NRaW55aUBpbW9vYy5jb21cIn0iLCJqdGkiOiJiNmQ0ZTM0Mi0yNWU1LTQwOGItYTJlMi0xNTI1ZDIyNmE3NjUiLCJleHAiOjE2NTY0MzIwMDB9.A8Xauk27EBNFesTR5qysbEMCbEKEnhEyAO4Q_yNQAlES_WcsTapSRw8WBxUnjuveqJzLSOqn8tS6lu7QhG_BzsDTppnM-AqcE__9YNGA0TjiOHyE9eqWalm74kcY52bMFQgF_yRsZyzGCZq5fmhRlt_XvT_rfawrEai5eHMUYT9DYCny5yWeRlM2pliDSexahqYtjvSLBP8pyTVgEWk8p_ml4iF4fPWYJeryl1K46uV4wKOVJTbH45nczXECI51q5ZO8E5EQMrpwEXqT17BBSLxihdBIomS_zHeXS3QsSCXoSnhxhRJP0QjDPnJLCn6zoa4bZJkCtvlpAT4qpFuxBw

{
  "userId": 10,
  "balance": 2000
}