GET http://127.0.0.1:9001/gw/ecommerce-nacos-client/nacos-client/service-instance?serviceId=ecommerce-gateway
Accept: application/json
ecommerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiSW1vb2NRaW55aUBpbW9vYy5jb21cIn0iLCJqdGkiOiJiNmQ0ZTM0Mi0yNWU1LTQwOGItYTJlMi0xNTI1ZDIyNmE3NjUiLCJleHAiOjE2NTY0MzIwMDB9.A8Xauk27EBNFesTR5qysbEMCbEKEnhEyAO4Q_yNQAlES_WcsTapSRw8WBxUnjuveqJzLSOqn8tS6lu7QhG_BzsDTppnM-AqcE__9YNGA0TjiOHyE9eqWalm74kcY52bMFQgF_yRsZyzGCZq5fmhRlt_XvT_rfawrEai5eHMUYT9DYCny5yWeRlM2pliDSexahqYtjvSLBP8pyTVgEWk8p_ml4iF4fPWYJeryl1K46uV4wKOVJTbH45nczXECI51q5ZO8E5EQMrpwEXqT17BBSLxihdBIomS_zHeXS3QsSCXoSnhxhRJP0QjDPnJLCn6zoa4bZJkCtvlpAT4qpFuxBw
token: ir6